apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-demo
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: hub-spoke-dev
      - stage: hub-spoke-prod
      - stage: hub-spoke-staging
  template:
    metadata:
      name: kargo-demo-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-demo:{{stage}}
      labels:
        component: kargo-demo
    spec:
      project: default
      source:
        repoURL: https://github.com/danielloader/kargo-demo
        targetRevision: stage/{{stage}}
        path: stages/{{stage}}
      destination:
        name: '{{stage}}'
        namespace: kargo-demo
      syncPolicy:
        syncOptions:
        - CreateNamespace=true