on:
  push:
    branches:
      - main

name: Release
run-name: Release
jobs:
   
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_ACTION_TOKEN }}
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: 'npm'
          cache-dependency-path: '**/.github/workflows/release.yaml'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_ACTION_TOKEN }}
        run: >
          npx 
          -p @semantic-release/changelog
          -p @semantic-release/exec
          -p @semantic-release/git
          -p conventional-changelog-conventionalcommits
          semantic-release